version: 2.1

orbs:
  aws-s3: circleci/aws-s3@3.0.0

parameters:
  # This parameter is used to trigger the main workflow
  trigger:
    type: boolean
    default: true

#react_app_trigger_params

executors:
  node:
    docker:
      - image: circleci/node:12

jobs:
  trigger-workflows:
    #executor: node
    executor: node

    environment:
      AWS_REGION: ca-central-1
    steps:
      - checkout
      - run:
          name: Trigger workflows
          command: chmod +x .circleci/circle_trigger.sh && .circleci/circle_trigger.sh

#  commit-check:
#    docker:
#      - image: circleci/node:10
#
#    working_directory: ~/project
#
#    environment:
#      AWS_REGION: ca-central-1
#      # Specify service dependencies here if necessary
#      # CircleCI maintains a library of pre-built images
#      # documented at https://circleci.com/docs/2.0/circleci-images/
#      # - image: circleci/mongo:3.4.4
#
#
#
#    steps:
#      - checkout
#      - run:
#        command: |
#          .circleci/commit_check.sh

  build-and-deploy-react-s3:
    executor: node

    parameters:
      # A parameter per package
      app_name:
        type: string
        #default: false


    #working_directory: ~/project/apps/<< parameters.app_name >>

    environment:
      AWS_REGION: #region
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "~/project/apps/<<parameters.app_name>>/package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      #  Install Dependencies

      - run:
          name: Install dependencies with NPM
          command: cd ~/project/apps/<<parameters.app_name>> && yarn install # replace with `yarn install` if using yarn

      - save_cache:
          paths:
            - ~/project/apps/<<parameters.app_name>>/node_modules
          key: v1-dependencies-{{ checksum "~/project/apps/<<parameters.app_name>>/package.json" }}

      # Buil app
      - run: cd ~/project/apps/<<parameters.app_name>> && yarn run build

      - aws-s3/sync:
          aws-access-key-id: PROD_AWS_ACCESS_KEY_ID
          aws-secret-access-key: PROD_AWS_SECRET_ACCESS_KEY
          from: ~/project/apps/<<parameters.app_name>>/build/
          to: "s3://<<parameters.app_name>>.#apex_domain"
          arguments: |
            --acl public-read \


workflows:
  version: 2.0

  ci:
    when: << pipeline.parameters.trigger >>
    jobs:
      - trigger-workflows

#react_app_workflows
