version: 2.1
orbs:
  aws-s3: circleci/aws-s3@3.0.0
jobs:
  build-and-deploy:
    docker:
      - image: circleci/node:10

    working_directory: ~/repo

    environment:
      AWS_REGION: ca-central-1
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      #  Install Dependencies

      - run:
          name: Install dependencies with NPM
          command: yarn install # replace with `yarn install` if using yarn

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # Buil app
      - run: yarn run build

      - aws-s3/sync:
          aws-access-key-id: PROD_AWS_ACCESS_KEY_ID
          aws-secret-access-key: PROD_AWS_SECRET_ACCESS_KEY
          from: ~/repo/build/
          to: "s3://basic-ci.skunk.services"
          arguments: |
            --acl public-read \


workflows:
  version: 2.0
  workflow:
    jobs:
      - build-and-deploy:
          filters:
            branches:
              only: main # set so only changes to master will be deployed
